### ISSUE TITLE
Add expath-pkg.xml, repo.xml, etc. to .gitignore

### ISSUE THREAD

**Issue by joewiz** [eXist-db/website#2]
To ensure generated files like `expath-pkg.xml`, `repo.xml`, and presumably also bower/grunt products are not committed to source.

**Comment by ljo** [comment]
There is a .gitignore file which covers most of the npm/js stuff. For the templates it was just not enough time to clean it all today. I had to focus on the most annoying stuff and make the source available.

**Comment by joewiz** [comment]
@ljo Great, thank you! Please don't treat the issues I filed as a complaint or as indicating any kind of urgency. I thought I'd just capture a few observations for future consideration/action.

**Comment by joewiz** [comment]
As @wolfgangmm observed in #5:

> I think the minimized files may be generated by the grunt build, so could be added to gitignore instead.

**Comment by joewiz** [comment]
Closed by #5.
