### ISSUE TITLE
[BUG] Escaping special characters in searches

### ISSUE THREAD

**Issue by lguariento** [eXist-db/website#28]
When the input search string contains a parenthesis Lucene interprets it as an unescaped special character. For instance, searching for test) or httpclient() .

**Comment by line-o** [comment]
I assume you propose that we escape any special character from searches.
Followign exceptions could be useful (even used)
- double quotes for phrase searches: `"this is my search term"`
- asterisk for fuzzy searches: `*`
- how about question marks: `?`

**Comment by lguariento** [comment]
Do you know of a way of escaping them other than JavaScript? How I'd do it is by adding something like 'on submit, look for these characters and add a \ before them'.

```
document.getElementById("search_button").addEventListener('click', function () {
  let text = document.getElementById('search_field_id').value;
  let regex = /:/gi; <- the regex. In this case I am escaping the semicolon
  let new_text = text.replaceAll(regex, "\\:");
  document.getElementById('search_field_id').value =  new_text;
});
```

**Comment by line-o** [comment]
The special characters in the search term should be escaped on the server (in xquery).

**Comment by line-o** [comment]
Can you dig up where is the search query is being sent to?

**Comment by lguariento** [comment]
[Here it is](https://github.com/eXist-db/documentation/blob/a48215e27a8d401d960b46b6aac4aaaf26f69fee/src/main/xar-resources/modules/search.xql#L30).

**Comment by lguariento** [comment]
Actually this issue is about the /documentation repository rather than this, I think.

**Comment by line-o** [comment]
Yep, I agree. And it will then also be fixed for both.

**Comment by lguariento** [comment]
Closing this and opening [this](https://github.com/eXist-db/documentation/issues/744).
