### ISSUE TITLE
Update eXist-db version on www.exist-db.org

### ISSUE THREAD

**Issue by adamretter** [eXist-db/website#8]
The version of eXist-db powering www.exist-db.org seems to be rather old, also the apps on demo.exist-db.org seem quite outdated. I note that eXide is now at version 2.4.0, but demo.exist-db.org only provides 2.1.3.

**Comment by wolfgangmm** [comment]
Ok, I'll look into updating the website and apps tomorrow.

**Comment by dizzzz** [comment]
@wolfgangmm am I correct that you upgraded the server?

**Comment by wolfgangmm** [comment]
@dizzzz yes, the server runs eXist 3.5.0 now.
