### ISSUE TITLE
Update timeline

### ISSUE THREAD

**Issue by miljanuscumlic** [eXist-db/website#9]
Latest announcement on timetunnel.html is the release of eXist-db v3.2.0. It would be nice to see a new release on it.

**Comment by dizzzz** [comment]
Please could you add a URL? I don't know this page....

**Comment by miljanuscumlic** [comment]
It's http://www.exist-db.org/exist/apps/homepage/timetunnel.html, but you figured it out. :)

**Comment by line-o** [comment]
I believe this was fixed in the meantime.

**Comment by lguariento** [comment]
It's also been [re-written](https://github.com/eXist-db/website/pull/26) in the meantime of course, so I think this is clearly fixed.

**Comment by joewiz** [comment]
Closed by https://github.com/eXist-db/website/pull/26, if not before.
